export const endpoints = {
  auth: {
    login:   '/auth/login',
    refresh: '/auth/token/refresh',
    me:      '/users/me',
  },
  users: {
    list:           '/users',
    detail:         (id: string) => `/users/${id}`,
    create:         '/users',
    update:         (id: string) => `/users/${id}`,
    delete:         (id: string) => `/users/${id}`,
    changePassword: '/users/change-password',
    carga:          (userId: string) => `/users/${userId}/carga`,
  },
  assets: {
    list:    '/assets',
    detail:  (id: string) => `/assets/${id}`,
    create:  '/assets',
    update:  (id: string) => `/assets/${id}`,
    delete:  (id: string) => `/assets/${id}`,
    writeOff:(id: string) => `/assets/${id}/write-off`,
    history: (id: string) => `/assets/${id}/history`,
    custody: (id: string) => `/assets/${id}/custody`,
  },
  categories: {
    list:   '/categories',
    detail: (id: string) => `/categories/${id}`,
    create: '/categories',
    update: (id: string) => `/categories/${id}`,
    delete: (id: string) => `/categories/${id}`,
  },
  locations: {
    list:   '/locations',
    detail: (id: string) => `/locations/${id}`,
    create: '/locations',
    update: (id: string) => `/locations/${id}`,
    delete: (id: string) => `/locations/${id}`,
  },
  custody: {
    list:    '/custody',
    assign:  '/custody',
    release: (assetId: string) => `/custody/assets/${assetId}`,
  },
  movements: {
    list:     '/movements',
    register: '/movements',
  },
  maintenance: {
    list:         '/maintenance',
    detail:       (id: string) => `/maintenance/${id}`,
    create:       '/maintenance',
    updateStatus: (id: string) => `/maintenance/${id}/status`,
    complete:     (id: string) => `/maintenance/${id}/complete`,
  },
  inventory: {
    list:       '/inventory',
    detail:     (id: string) => `/inventory/${id}`,
    create:     '/inventory',
    start:      (id: string) => `/inventory/${id}/start`,
    complete:   (id: string) => `/inventory/${id}/complete`,
    cancel:     (id: string) => `/inventory/${id}/cancel`,
    items:      (id: string) => `/inventory/${id}/items`,
    verifyItem: (id: string) => `/inventory/${id}/verify`,
  },
};
